services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+psycopg://oms_user:oms_pass@postgres:5432/oms_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - TIMEZONE=Asia/Kolkata
      - CURRENCY=INR
      - PAYMENT_GATEWAY_BASE_URL=http://payment-gateway:9000
      - INVOICE_OUTPUT_DIR=/data/invoices
    volumes:
      - .:/app
      - ./invoices:/data/invoices
    depends_on:
      - postgres
      - rabbitmq
      - payment-gateway

  worker:
    build: .
    command: celery -A worker.celery_app.celery_app worker --loglevel=INFO
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql+psycopg://oms_user:oms_pass@postgres:5432/oms_db
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
      - TIMEZONE=Asia/Kolkata
      - CURRENCY=INR
      - PAYMENT_GATEWAY_BASE_URL=http://payment-gateway:9000
      - INVOICE_OUTPUT_DIR=/data/invoices
    volumes:
      - .:/app
      - ./invoices:/data/invoices
    depends_on:
      - rabbitmq
      - postgres

  payment-gateway:
    build: .
    command: uvicorn payment_gateway_service.main:app --host 0.0.0.0 --port 9000
    ports:
      - "9000:9000"
    volumes:
      - .:/app

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=oms_db
      - POSTGRES_USER=oms_user
      - POSTGRES_PASSWORD=oms_pass
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  pg_data:
