from enum import Enum


class OrderState(str, Enum):
	PENDING_PAYMENT = "PENDING_PAYMENT"
	PAID = "PAID"
	PROCESSING_IN_WAREHOUSE = "PROCESSING_IN_WAREHOUSE"
	SHIPPED = "SHIPPED"
	DELIVERED = "DELIVERED"
	CANCELLED = "CANCELLED"


class ReturnState(str, Enum):
	REQUESTED = "REQUESTED"
	APPROVED = "APPROVED"
	REJECTED = "REJECTED"
	IN_TRANSIT = "IN_TRANSIT"
	RECEIVED = "RECEIVED"
	COMPLETED = "COMPLETED"
